name = "Academic"
license = "MIT"
licenselink = "https://github.com/gcushen/hugo-academic/blob/master/LICENSE.md"
description = "Easily create beautifully simple academic or personal sites"
homepage = "https://github.com/gcushen/hugo-academic"
min_version = 0.30
tags = ["academic",
        "portfolio",
        "responsive",
        "student",
        "personal",
        "university",
        "blog",
        "minimal"
        ]
features = ["academic profile",
            "research publication system",
            "projects",
            "blog",
            "teaching",
            "contact"
            ]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""

[[menu.main]]
    name = "Andrew's Data Science Blog"
    
[[menu.main]]
    name = "My Github"
    url = "https://github.com/agehma64/Myblog-"
    
[[photo.main]]
    url = "https://www.facebook.com/photo.php?fbid=107213249696548&set=a.107202966364243.1073741826.100012236195395&type=3" 
    